
INSERT INTO public.funding_opportunities (fon, title, activity_code, announcement_type, participating_orgs, purpose, posted_date, open_date, expiration_date, due_dates, url, status, relevance_tags, eligible_activity_codes, budget_ceiling, notes)
VALUES 
(
  'RFA-NS-25-016',
  'BRAIN Initiative: Promoting Health for All Through BRAIN Technology Partnerships',
  'R34',
  'New',
  ARRAY['NINDS', 'NEI', 'NIA', 'NIAAA', 'NIBIB', 'NICHD', 'NIDCD', 'NIDA', 'NIMH', 'NCCIH'],
  'This NOFO is intended for investigators at resource-limited institutions to adopt and integrate BRAIN Initiative resources into their research. Supports two-way knowledge transfer between PI and BRAIN disseminator.',
  '2024-11-22',
  '2025-05-17',
  '2026-06-18',
  '[{"date": "2025-06-17", "type": "New"}, {"date": "2026-06-17", "type": "New/Resubmission"}]'::jsonb,
  'https://grants.nih.gov/grants/guide/rfa-files/RFA-NS-25-016.html',
  'open',
  ARRAY['BRAIN Initiative', 'Technology Partnerships', 'Resource-Limited Institutions', 'Neuroscience'],
  ARRAY['R34'],
  NULL,
  'R34 planning grant. Activities may include pilot efforts to establish feasibility for future larger-scale research utilizing BRAIN Initiative resources.'
),
(
  'RFA-NS-25-019',
  'BRAIN Initiative: Development and Validation of Novel Tools to Probe Cell-Specific and Circuit-Specific Processes in the Brain',
  'U01',
  'New',
  ARRAY['NINDS', 'NIMH', 'NIDA', 'NIAAA', 'NIA', 'NICHD'],
  'Supports the development and validation of novel tools and technologies to facilitate the detailed analysis of complex neural circuits and brain function.',
  '2024-12-05',
  '2025-06-01',
  '2027-06-02',
  '[{"date": "2025-10-14", "type": "New"}]'::jsonb,
  'https://grants.nih.gov/grants/guide/rfa-files/RFA-NS-25-019.html',
  'open',
  ARRAY['BRAIN Initiative', 'Tool Development', 'Neural Circuits', 'Neuroscience'],
  ARRAY['U01'],
  NULL,
  'Supports development of innovative technologies for brain research.'
),
(
  'RFA-MH-26-100',
  'BRAIN Initiative: Theories, Models and Methods for Analysis of Complex Data from the Brain',
  'R01',
  'Reissue',
  ARRAY['NIMH', 'NINDS', 'NIDA', 'NIA'],
  'Supports development of theories, computational models, and analytical tools to understand neural coding, dynamics, and connectivity.',
  '2025-01-15',
  '2025-06-05',
  '2027-09-08',
  '[{"date": "2025-10-05", "type": "New"}]'::jsonb,
  'https://grants.nih.gov/grants/guide/rfa-files/RFA-MH-26-100.html',
  'open',
  ARRAY['BRAIN Initiative', 'Computational Neuroscience', 'Data Analysis', 'Neural Dynamics'],
  ARRAY['R01'],
  500000,
  'Relevant for computational and data-intensive BBQS projects.'
),
(
  'RFA-DA-26-039',
  'BRAIN Initiative: Exploratory Team-Research BRAIN Circuit Programs',
  'U01',
  'New',
  ARRAY['NIDA', 'NIMH', 'NINDS', 'NEI'],
  'Supports teams of investigators to explore circuit function underlying behavior using innovative, cross-disciplinary approaches.',
  '2025-02-10',
  '2025-07-01',
  '2027-07-02',
  '[{"date": "2025-11-15", "type": "New"}]'::jsonb,
  'https://grants.nih.gov/grants/guide/rfa-files/RFA-DA-26-039.html',
  'open',
  ARRAY['BRAIN Initiative', 'Circuit Neuroscience', 'Team Science', 'Behavior'],
  ARRAY['U01'],
  1500000,
  'Multi-PI team grants. Highly relevant for cross-species behavioral circuit studies.'
),
(
  'PAR-25-200',
  'BRAIN Initiative: Research on the Ethical Implications of Advancements in Neurotechnology and Brain Science',
  'R01',
  'New',
  ARRAY['NIMH', 'NINDS', 'NIBIB'],
  'Supports research that addresses ethical issues arising from BRAIN Initiative-funded technologies, including neuroethics of data sharing and privacy.',
  '2025-03-01',
  '2025-06-16',
  '2028-01-08',
  '[{"date": "2025-10-05", "type": "New"}, {"date": "2026-06-05", "type": "New/Resubmission"}]'::jsonb,
  'https://grants.nih.gov/grants/guide/pa-files/PAR-25-200.html',
  'open',
  ARRAY['BRAIN Initiative', 'Neuroethics', 'Data Privacy', 'Neurotechnology'],
  ARRAY['R01'],
  300000,
  'Relevant to data sharing policy and privacy-related BBQS efforts.'
);
