name: Mirror to nadernik/brain-bbq-clone-mirror

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror
        run: |
          git clone --bare https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/brain-bbqs/brain-bbq-clone.git repo
          cd repo
          git push --force --all https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/nadernik/brain-bbq-clone-mirror.git
          git push --force --tags https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/nadernik/brain-bbq-clone-mirror.git
